services:
  siteproxy:
    image: ghcr.io/janver/siteproxy:latest
    container_name: siteproxy-node
    restart: unless-stopped
    ports:
      - 127.0.0.1:5006:5006
    volumes:
      - ../config.json:/app/config.json:ro
    command: ["node", "/app/bundle.mjs"]
